GET http://localhost:5236/users

###
GET http://localhost:5236/users/3

###
POST http://localhost:5236/users
Content-Type:  application/json

{
    "username": "gio_",
    "password": "1234567",
    "userType": "User"
}